In [0]:
# Importing necessary libraries

import torch
import pandas as pd

Refer https://www.kaggle.com/general/74235 to find out how to generate a Kaggle API key.

In [0]:
! pip install -q kaggle

In [0]:
from google.colab import files

In [4]:
files.upload()

Saving kaggle (1).json to kaggle (1).json


{'kaggle (1).json': b'{"username":"iiverveii","key":"6f1b8e878dba0ffd154a133c58cbe9c6"}'}

In [9]:
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [0]:
! chmod 600 ~/.kaggle/kaggle.json

In [11]:
# Downloading a linear regression dataset from Kaggle

! kaggle datasets download -d aungpyaeap/fish-market

  0% 0.00/2.39k [00:00<?, ?B/s]
100% 2.39k/2.39k [00:00<00:00, 5.17MB/s]


In [12]:
! unzip fish-market.zip

Archive:  fish-market.zip
  inflating: Fish.csv                


In [225]:
# Converting a CSV file to a Pandas dataframe

dataframe = pd.read_csv('Fish.csv').drop('Species', axis=1)
dataframe.head()

Weight  Length1  Length2  Length3   Height   Width
0   242.0     23.2     25.4     30.0  11.5200  4.0200
1   290.0     24.0     26.3     31.2  12.4800  4.3056
2   340.0     23.9     26.5     31.1  12.3778  4.6961
3   363.0     26.3     29.0     33.5  12.7300  4.4555
4   430.0     26.5     29.0     34.0  12.4440  5.1340

In [226]:
# Creating arrays from the dataframe

inputs = dataframe.drop('Weight', axis = 1).values
target = dataframe[['Weight']].values
inputs.shape, target.shape

((159, 5), (159, 1))

In [227]:
num_cols = len(dataframe.drop('Weight', axis = 1).columns)
num_cols

5

In [228]:
# Converting inputs and the output to a PyTorch's tensors
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)
inputs.dtype

torch.float64

In [229]:
# Generating random weights and biases

weights = torch.randn(1, num_cols, requires_grad = True, dtype = torch.float64)
biases = torch.randn(1, requires_grad = True, dtype = torch.float64)
weights, biases

(tensor([[-1.6104, -0.7474, -0.0821,  1.0922,  0.0979]], dtype=torch.float64,
        requires_grad=True),
 tensor([0.2544], dtype=torch.float64, requires_grad=True))

In [0]:
# Decide learning rate
learning_rate = 3e-4

In [0]:
# Train for some epochs
def train(epochs, inputs, target, weights, biases):
  # Simple matrix multiplication
  def model(x):
    return x @ weights.t() + biases

  # Loss function calculates mean squared error
  def mse_loss(t1, t2):
    return torch.sum((t1 - t2) ** 2) / t1.numel()

  for epoch in range(1, epochs+1):
    # Generate predictions
    predictions = model(inputs)

    # Calculate loss
    loss = mse_loss(predictions, target)

    # Print loss
    if (epoch) % 20 == 0:
      print('Epoch {} : Loss : {}'.format(epoch, loss))

    # Compute gradients
    loss.backward()

    # Adjust weights and reset gradients
    with torch.no_grad():
      weights -= weights.grad * learning_rate
      biases -= biases.grad * learning_rate
      weights.grad.zero_()
      biases.grad.zero_()

In [243]:
# Train model
train(300, inputs, target, weights, biases)

Epoch 20 : Loss : 43280.9778294256
Epoch 40 : Loss : 43185.436902032
Epoch 60 : Loss : 43090.296813099405
Epoch 80 : Loss : 42995.55468705417
Epoch 100 : Loss : 42901.207721522296
Epoch 120 : Loss : 42807.25317677296
Epoch 140 : Loss : 42713.6883675589
Epoch 160 : Loss : 42620.510656788465
Epoch 180 : Loss : 42527.71745059843
Epoch 200 : Loss : 42435.30619449789
Epoch 220 : Loss : 42343.27437033204
Epoch 240 : Loss : 42251.61949387291
Epoch 260 : Loss : 42160.33911289129
Epoch 280 : Loss : 42069.43080559659
Epoch 300 : Loss : 41978.89217935966


In [244]:
# Get final predictions

predictions = model(inputs)
predictions

tensor([[428.9061],
        [451.3175],
        [452.5279],
        [490.9221],
        [490.0836],
        [507.8457],
        [517.1240],
        [506.5316],
        [522.1837],
        [535.5873],
        [537.6008],
        [541.4156],
        [540.0524],
        [548.4645],
        [560.3274],
        [567.6454],
        [573.5304],
        [572.9689],
        [590.2239],
        [579.8197],
        [589.8543],
        [602.0386],
        [598.3888],
        [603.7283],
        [612.3159],
        [612.1519],
        [616.4731],
        [628.5121],
        [634.9707],
        [671.4011],
        [681.0267],
        [682.0713],
        [706.9775],
        [728.4066],
        [719.2019],
        [199.4475],
        [267.8987],
        [283.4204],
        [295.6558],
        [310.7585],
        [318.2658],
        [316.6847],
        [317.5570],
        [330.2064],
        [342.4970],
        [346.4763],
        [346.6909],
        [348.1296],
        [371.7451],
        [361.9685],


In [245]:
target

tensor([[ 242.0000],
        [ 290.0000],
        [ 340.0000],
        [ 363.0000],
        [ 430.0000],
        [ 450.0000],
        [ 500.0000],
        [ 390.0000],
        [ 450.0000],
        [ 500.0000],
        [ 475.0000],
        [ 500.0000],
        [ 500.0000],
        [ 340.0000],
        [ 600.0000],
        [ 600.0000],
        [ 700.0000],
        [ 700.0000],
        [ 610.0000],
        [ 650.0000],
        [ 575.0000],
        [ 685.0000],
        [ 620.0000],
        [ 680.0000],
        [ 700.0000],
        [ 725.0000],
        [ 720.0000],
        [ 714.0000],
        [ 850.0000],
        [1000.0000],
        [ 920.0000],
        [ 955.0000],
        [ 925.0000],
        [ 975.0000],
        [ 950.0000],
        [  40.0000],
        [  69.0000],
        [  78.0000],
        [  87.0000],
        [ 120.0000],
        [   0.0000],
        [ 110.0000],
        [ 120.0000],
        [ 150.0000],
        [ 145.0000],
        [ 160.0000],
        [ 140.0000],
        [ 160

Clearly, the simple model did not work. Therefore we have to look for a different way.